name: Automatic Testing for Resource Management Web App

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from GitHub Repo
        uses: actions/checkout@v3

      - name: Setup Node.js in Ubuntu
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"  # Cache dependencies for faster builds

      - name: Remove existing node_modules folder
        run: rm -rf node_modules

      - name: Install dependencies based on package.json
        run: npm install

      - name: Verify successful installation
        run: npm list --depth=0  # Prints installed packages to check if dependencies are installed correctly

      - name: Run backend tests in "tests" folder
        run: npm run backend-test
